FROM node:8

WORKDIR /usr/src/app

# Copy the package files separately,
# so we only install when something changes in one of those files
COPY proxy/package.json .
COPY proxy/package-lock.json .

RUN npm install

COPY proxy/. .

EXPOSE 5000

CMD [ "npm", "start" ]