version: '3'
services:
  admin:
    image: azure-search-admin
    build:
      context: ./admin
      dockerfile: dockerfile.admin
    depends_on:
      - proxy
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./admin/src:/usr/src/app/src
      - ./admin/public:/usr/src/app/public
  proxy:
    build:
      context: ./proxy
      dockerfile: dockerfile.proxy
    image: azure-search-proxy
    ports:
      - 5000:5000
    restart: always
